
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "abc805aa6f0614bd498e9869a16b7cee76a59ba8",
 "version": "3.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
